#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - apt-transport-https
  - curl

write_files:
  - path: /etc/kubernetes/setup.sh
    content: |
      #!/bin/bash
      # Disable swap
      swapoff -a
      sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      
      # Install Kubernetes packages
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
      apt-get update
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl

      kubeadm join 10.0.100.97:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>

      # Enable kubelet service
      systemctl enable kubelet && systemctl start kubelet

  - path: /etc/systemd/system/k8s-setup.service
    content: |
      [Unit]
      Description=Kubernetes Setup
      After=docker.service

      [Service]
      ExecStart=/bin/bash /etc/kubernetes/setup.sh
      Restart=on-failure
      RestartSec=10

      [Install]
      WantedBy=multi-user.target

runcmd:
  - systemctl daemon-reload
  - systemctl enable k8s-setup.service
  - systemctl start k8s-setup.service

final_message: "Kubernetes setup is complete!"
